version: '3'
services:
  ros-nu20:
    restart: always
    container_name: ros-nu20
    build: .
    volumes:
      - catkin_ws:/catkin_ws
    ports:
      - "11311:11311"
    depends_on:
      - novnc
    command:
      - /home/ubuntu/setup_robot_programming/entrypoint.sh
      - roscore

  rviz:
    restart: always
    container_name: rviz
    build: .
    volumes:
      - catkin_ws:/catkin_ws
    environment:
      - ROS_HOSTNAME=rviz
      - ROS_MASTER_URI=http://ros-nu20:11311
      - DISPLAY=novnc:0.0
    depends_on:
      - ros-nu20
      - novnc
    command:
      - rviz

  novnc:
    image: gramaziokohler/novnc:latest
    ports:
      - "8080:8080"

volumes:
  catkin_ws: