version: '2'
services:
  ros-master:
    image: gramaziokohler/ros-base
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-panda-planner
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  panda-demo:
    image: gramaziokohler/ros-panda-planner
    container_name: panda-demo
    environment:
      - ROS_HOSTNAME=panda-demo
      - ROS_MASTER_URI=http://ros-master:11311
      - DISPLAY=gui:0.0
    depends_on:
      - ros-master
      - gui
    command:
      - roslaunch
      - --wait
      - panda_moveit_config
      - demo.launch

  gui:
    image: gramaziokohler/novnc:latest
    ports:
      - "8080:8080"
