version: '3'
services:
  melodicvnc:
    restart: always
    container_name: melodicvnc
    build: .
    volumes:
      - catkin_ws:/catkin_ws
    ports:
      - "2000:22"
      - "8000:80"
      - "5900:5900"
      - "9090:9090" 
      - "50001:50001"
    environment:
      - shm-size="512m"
      - RESOLUTION=1280x1024
      - USER=ubuntu
      - TZ=Asia/Tokyo
    #command:
      #- /home/ubuntu/setup_robot_programming/entrypoint.sh

volumes:
  catkin_ws: